StageId = 1;
VelocityId = 1;
TempEaEvaluation = transpose(polyval(PolyEaCoefficients{StageId}, TargetConversions(:)));
TempAEvaluation = exp(transpose(polyval(PolyACoefficients{StageId}, TempEaEvaluation(:))));
ExperimentalDTG = [diff(TargetConversions(1, :)) ./ diff(TargetConversionsTemperatures{VelocityId, StageId}(1, :)), 0];
SBStartPoints = [1 1 1 1];
TSBStartPoints = [1 1 1];
CLStartPoints = [1 1 1 1];
X = [transpose(TempAEvaluation), transpose(TargetConversions), transpose(TempEaEvaluation), transpose(TargetConversionsTemperatures{VelocityId, StageId}(1, :))];
SBFitterModel = @(X, Parameters) X(:, 1) .* SestakBerggren(X(:, 2), Parameters) .* exp(-X(:, 3) ./ (R .* X(:, 4))) ./ InitialVelocities(VelocityId);
TSBFitterModel = @(X, Parameters) X(:, 1) .* TruncatedSestakBerggren(X(:, 2), Parameters) .* exp(-X(:, 3) ./ (R .* X(:, 4))) ./ InitialVelocities(VelocityId);
CLFitterModel = @(X, Parameters) X(:, 1) .* CaiLiu(X(:, 2), Parameters) .* exp(-X(:, 3) ./ (R .* X(:, 4))) ./ InitialVelocities(VelocityId);
[SBResultParameters, SBGlobalMinimum] = fminsearch(@(Parameters) norm(ExperimentalDTG - transpose(SBFitterModel(X, Parameters))), SBStartPoints);
[TSBResultParameters, TSBGlobalMinimum] = fminsearch(@(Parameters) norm(ExperimentalDTG - transpose(TSBFitterModel(X, Parameters))), TSBStartPoints);
[CLResultParameters, CLGlobalMinimum] = fminsearch(@(Parameters) norm(ExperimentalDTG - transpose(CLFitterModel(X, Parameters))), CLStartPoints);
SBTheoreticalDTG = transpose(SBFitterModel(X, SBResultParameters));
TSBTheoreticalDTG = transpose(TSBFitterModel(X, TSBResultParameters));
CLTheoreticalDTG = transpose(CLFitterModel(X, CLResultParameters));
FigureNumber = FigureNumber + 1;
figure(FigureNumber);
colororder({'#0C5DA5', '#00B945', '#F94144', '#B83DBA'});
grid on;
plot(TargetConversionsTemperatures{VelocityId, StageId}(1, :), ExperimentalDTG, 'LineStyle', '-');
hold on;
plot(TargetConversionsTemperatures{VelocityId, StageId}(1, :), SBTheoreticalDTG, 'LineStyle', '--');
plot(TargetConversionsTemperatures{VelocityId, StageId}(1, :), TSBTheoreticalDTG, 'LineStyle', '-.');
plot(TargetConversionsTemperatures{VelocityId, StageId}(1, :), CLTheoreticalDTG, 'LineStyle', ':');
hold off;
legend({'DTG', 'Sestak-Berggren', 'Truncated Sestak-Berggren', 'Cai-Liu'}, 'Location', 'best', 'NumColumns', 1);
ylabel('$\frac{dm}{dT}, \frac{\%}{K}$', 'Interpreter', 'LaTex', 'FontSize', 14);
xlabel('T, K', 'FontSize', 14);
title(sprintf('Flexible Function Fitting, Stage = %.d, Velocity = %.d', StageId, InitialVelocities(VelocityId)), "FontSize", 12, "FontWeight", "normal");
disp('Sestak-Berggren Fit:');
disp('f(a) = c * a ^ m * (1 - a) ^ n * (-ln(1 - a)) ^ p');
fprintf('R2 = %.4f | c = %.6f, m = %.6f, n = %.6f, p = %.6f\n', ComputeR2(ExperimentalDTG, SBTheoreticalDTG), SBResultParameters);
disp('Truncated Sestak-Berggren Fit:');
disp('f(a) = c * a ^ m * (1 - a) ^ n');
fprintf('R2 = %.4f | c = %.6f, m = %.6f, n = %.6f\n', ComputeR2(ExperimentalDTG, TSBTheoreticalDTG), TSBResultParameters);
disp('Cai-Liu Fit:');
disp('f(a) = c * a ^ m * (1 - q * a) ^ n');
fprintf('R2 = %.4f | c = %.6f, m = %.6f, q = %.6f, n = %.6f\n', ComputeR2(ExperimentalDTG, CLTheoreticalDTG), CLResultParameters);